blog/urls.py
from django.urls import path, include
from .views import (PostListView, PostDetailView, PostCreateView, 
	PostUpdateView, PostDeleteView, UserPostListView)
from . import views

app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='blog-about'),
]

cvdigital/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('measurements/', include('geodjango.urls')),
    path('jsprojects/', include('jsprojects.urls')),
    path('img_classifier/', include('img_classifier.urls')),
    path('blog/', include('blog.urls')),
    # path('iris/', include('iris.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('profile/', user_views.profile, name='profile'),
    path('digits-api/', include('digit_classifier.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('crypto-tracker/', include('crypto_tracker.urls')),

]

# if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name= 'home'
urlpatterns = [
    path('', views.home, name='main'),
]

jsprojects/urls.py
from django.urls import path
from . import views

app_name= 'jsprojects'
urlpatterns = [
    path('', views.home, name='main'),
    path('background-color/', views.bg_color, name='bg-color'),
    path('background-video/', views.bg_video, name='bg-video'),
]

jsprojects/models.py
from django.db import models

# Create your models here.

jsprojects/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'jsprojects/main.html')

def bg_color(request):
    return render(request, 'jsprojects/bg-color.html')

def bg_video(request):
    return render(request, 'jsprojects/bg-video.html')

jsprojects/templates/jsprojects/base.html
{% extends "home/base_bootstrap.html" %}

{% load static %}

{% block title %}JavaScript{% endblock %}

{% block head %}
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'jsprojects/css/styles.css' %}" type="text/css">
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'jsprojects:main' %}"><span class="navbar-logo"><img src="{% static 'home\images\javascript-logo.png' %}"></img></span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home:main' %}">Portfolio <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'jsprojects:main' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Projects
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'jsprojects:bg-color' %}">Color Flipper</a>
            <a class="dropdown-item" href="{% url 'jsprojects:bg-video' %}">Background Video</a>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav ml-5">
        {% if user.is_authenticated %} 
        <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}">Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %} 
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}?next={{request.path}}">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
        {% endif %}
    </ul>
    </div>
  </nav>
{% endblock %}

jsprojects/templates/jsprojects/bg-color.html
{% extends "jsprojects/base.html" %}

{% load static %}

{% block content %}
    <div class="container">
        <div class="d-flex align-items-center justify-content-center vh-100">
            <div class="d-flex flex-column">
                <div class="mx-auto bg-dark bg-gradient text-white px-5 py-3 mb-3 rounded-pill">Background color : <span id="color">#5ABC936</span></div>
                <div id="btn" class="btn btn-outline-dark btn-lg mx-5">CLICK ME</div>
            </div>
        </div>
    </div>
    <script src="{% static 'jsprojects\js\bg-color.js' %}"></script>    
{% endblock %}

jsprojects/templates/jsprojects/bg-video.html
{% extends "jsprojects/base.html" %}

{% load static %}

{% block head %}
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link href="{% static 'jsprojects/css/styles.css' %}" rel="stylesheet">

{% endblock %}

{% block content %}
    <div class="preloader">
        {% comment %} <video muted autoplay loop>
            <source src="{% static 'jsprojects/videos/preloader.mp4' %}" type="video/mp4">
        </video> {% endcomment %}
        <iframe class="w-100 h-100" src="https://giphy.com/embed/TvLuZ00OIADoQ"></iframe>
    </div>
    <header>
        <div class="overlay d-none d-sm-block"></div>
        <video id="bg-video" muted autoplay loop>
            <source src="{% static 'jsprojects/videos/coral_reef.mp4' %}" type="video/mp4">
        </video>
    </header>
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-6 col-sm-3 align-self-end pb-3">
                <div class="btn-group mb-2" role="group" aria-label="Basic example">
                    <button id="btn-play" type="button" class="btn btn-primary">
                        <i class="fa fa-play"></i>
                    </button>
                    <button id="btn-pause" type="button" class="btn btn-danger">
                        <i class="fa fa-pause"></i>
                    </button>
                </div>
            </div>
            <div class="col-12 col-sm-6">
                <div class="title w-100 text-white text-center title-bg p-3 rounded">
                    <h4 class="display-5">Background Video</h4>
                    <p class="lead mb-0">Vanilla JavaScript and Bootstrap</p>
                </div>
            </div>
            <div class="col-6 col-sm-3 align-self-end pb-3">
                <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
                    <input type="radio" class="btn-check" name="btnradio" id="btnradio1" autocomplete="off" checked>
                    <label class="btn btn-primary" for="btnradio1">Coral</label>
                    
                    <input type="radio" class="btn-check" name="btnradio" id="btnradio2" autocomplete="off">
                    <label class="btn btn-primary" for="btnradio2">Forrest</label>
                    
                    <input type="radio" class="btn-check" name="btnradio" id="btnradio3" autocomplete="off">
                    <label class="btn btn-primary" for="btnradio3">Road</label>

                    <input type="radio" class="btn-check" name="btnradio" id="btnradio4" autocomplete="off">
                    <label class="btn btn-primary" for="btnradio4">Bird</label>
                </div>
            </div>
        </div>
    </div>  
    <footer class="fixed-bottom">
        <a href="https://giphy.com/gifs/TvLuZ00OIADoQ">via GIPHY</a>
    </p></footer>
{% endblock %}

{% block scripts %}
<script src="{% static 'jsprojects\js\bg-video.js' %}"></script>
{% endblock %}

jsprojects/templates/jsprojects/main.html
{% extends "jsprojects/base.html" %}

{% load static %}

{% block content %}

<div class="container">
    <div class="row mt-5 pt-5 bg-gradient-primary">
        <div class="col-md-4">
            <div class="card mb-4 box-shadow"> 
                <a href="{% url 'jsprojects:bg-color' %}">
                    <img class="card-img-top" src="{% static 'jsprojects/images/bg-color.png' %}" alt="">
                </a>
                <div class="card-body">
                    <h6 class="card-title">Random background color generator</h6>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4 box-shadow"> 
                <a href="{% url 'jsprojects:bg-video' %}">
                    <img class="card-img-top" src="{% static 'jsprojects/images/bg-video.png' %}" alt="">
                </a>
                <div class="card-body">
                    <h6 class="card-title">Background video with play and pause control. Multiple video source switching.</h6>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4 box-shadow"> 
                <img class="card-img-top" src="{% static 'jsprojects/images/coming-soon.png' %}" alt="Coming soon">
                <div class="card-body">
                    <h6 class="card-title">Coming Soon</h6>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <div class="card mb-4 box-shadow"> 
                <img class="card-img-top" src="{% static 'jsprojects/images/coming-soon.png' %}" alt="Coming soon">
                <div class="card-body">
                    <h6 class="card-title">Coming Soon</h6>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">  
                <img class="card-img-top" src="{% static 'jsprojects/images/coming-soon.png' %}" alt="Coming soon">
                <div class="card-body">
                    <h6 class="card-title">Coming Soon</h6>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4 box-shadow"> 
                <img class="card-img-top" src="{% static 'jsprojects/images/coming-soon.png' %}" alt="Coming soon">
                <div class="card-body">
                    <h6 class="card-title">Coming Soon</h6>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}