blog/urls.py
from django.urls import path, include
from .views import (PostListView, PostDetailView, PostCreateView, 
	PostUpdateView, PostDeleteView, UserPostListView)
from . import views

app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='blog-about'),
]

cvdigital/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('measurements/', include('geodjango.urls')),
    path('jsprojects/', include('jsprojects.urls')),
    path('img_classifier/', include('img_classifier.urls')),
    path('blog/', include('blog.urls')),
    # path('iris/', include('iris.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('profile/', user_views.profile, name='profile'),
    path('digits-api/', include('digit_classifier.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('crypto-tracker/', include('crypto_tracker.urls')),

]

# if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geodjango/urls.py
from django.urls import path
from .views import calculate_distance_view


app_name = 'geodjango'

urlpatterns = [
    path('', calculate_distance_view, name='calculate_view')
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name= 'home'
urlpatterns = [
    path('', views.home, name='main'),
]

img_classifier/urls.py
from django.urls import path
from . import views


app_name = 'img_classifier'

urlpatterns = [
    path('', views.index, name='main')
]

jsprojects/urls.py
from django.urls import path
from . import views

app_name= 'jsprojects'
urlpatterns = [
    path('', views.home, name='main'),
    path('background-color/', views.bg_color, name='bg-color'),
    path('background-video/', views.bg_video, name='bg-video'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home/main.html')

home/templates/home/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- LightBox --> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css" integrity="sha512-ZKX+BvQihRJPA8CROKBhDNvoc2aDMOdAlcm7TUQY+35XYtrd3yh95QOOhsPDQY9QnKE0Wqag9y38OIgEvb88cA==" crossorigin="anonymous" />


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">

    <!-- Font Awesome CSS -->    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">       
    
    <title>Alexander Marino | {% block title %}{% endblock %}</title> 

    {% block head %}{% endblock %}

</head>
<body>  
    {% block navbar %}{% endblock %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
            {{ message }}  	
            </div>
        {% endfor %}
    {% endif %}
    {% block background %}{% endblock %}
    {% block content %}{% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

home/templates/home/base_menu.html
{% extends "home/base_bootstrap.html" %}

{% load static %}

{% block head %}
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'home/css/main.css' %}" type="text/css">
{% endblock %}

{% block navbar %}
<div class="container">
    <nav class="navbar navbar-expand-sm navbar-dark my-3">
        <a class="navbar-brand text-white display-2" href="#">Portfolio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#about">About <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="appNavbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Apps
                    </a>
                    <div class="dropdown-menu" aria-labelledby="appNavbarDropdown">
                        <a class="dropdown-item" href="{% url 'geodjango:calculate_view' %}">GeoDjango</a>
                        <a class="dropdown-item" href="{% url 'jsprojects:main' %}">JavaScript</a>
                        <a class="dropdown-item" href="{% url 'img_classifier:main' %}">Image Classifier</a>
                        <a class="dropdown-item" href="{% url 'blog:blog-home' %}">Blog</a>

                        <a class="dropdown-item" href="#">Iris Classifier</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#publications">Publications</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#certificates">Certificates</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#photography">Photography</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-5">
                {% if user.is_authenticated %} 
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userNavbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img class="rounded-circle" height="40px" width="40px" src="{{ user.profile.image.url }}">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="userNavbarDropdown">
                        <a class="dropdown-item" href="{% url 'profile' %}">Edit Profile</a>
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    </div>
                </li>

                {% else %} 
                <li class="nav-item">
                    <a class="nav-link" href="login">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="register">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
{% endblock %}

home/templates/home/base_navbar.html
{% extends "home/base_bootstrap.html" %}

{% load static %}

{% block head %}
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'home/css/main.css' %}" type="text/css">
{% endblock %}

{% block navbar %}
<div class="container">
    <nav class="navbar navbar-expand-sm navbar-dark my-3">
        <a class="navbar-brand text-white display-2" href="#">Portfolio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#about">About <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="appNavbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Apps
                    </a>
                    <div class="dropdown-menu" aria-labelledby="appNavbarDropdown">
                        <a class="dropdown-item" href="{% url 'geodjango:calculate_view' %}">GeoDjango</a>
                        <a class="dropdown-item" href="{% url 'jsprojects:main' %}">JavaScript</a>
                        <a class="dropdown-item" href="{% url 'img_classifier:main' %}">Image Classifier</a>
                        <a class="dropdown-item" href="{% url 'blog:blog-home' %}">Blog</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#publications">Publications</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#certificates">Certificates</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#photography">Photography</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-5">
                {% if user.is_authenticated %} 
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userNavbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img class="rounded-circle" height="40px" width="40px" src="{{ user.profile.image.url }}">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="userNavbarDropdown">
                        <a class="dropdown-item" href="{% url 'profile' %}">Edit Profile</a>
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    </div>
                </li>

                {% else %} 
                <li class="nav-item">
                    <a class="nav-link" href="login">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="register">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
{% endblock %}