blog/urls.py
from django.urls import path, include
from .views import (PostListView, PostDetailView, PostCreateView, 
	PostUpdateView, PostDeleteView, UserPostListView)
from . import views

app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='blog-about'),
]

cvdigital/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('measurements/', include('geodjango.urls')),
    path('jsprojects/', include('jsprojects.urls')),
    path('img_classifier/', include('img_classifier.urls')),
    path('blog/', include('blog.urls')),
    # path('iris/', include('iris.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('profile/', user_views.profile, name='profile'),
    path('digits-api/', include('digit_classifier.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('crypto-tracker/', include('crypto_tracker.urls')),

]

# if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name= 'home'
urlpatterns = [
    path('', views.home, name='main'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
	"""Post"""
	title = models.CharField(max_length=100)
	content = models.TextField()
	date_posted = models.DateTimeField(default=timezone.now)
	author = models.ForeignKey(User, on_delete=models.CASCADE) # User comes from different table

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("blog:post-detail", kwargs={'pk': self.pk})

home/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post
from django.contrib.auth.models import User


class PostListView(ListView):
	model = Post
	template_name = 'blog/home.html'
	context_object_name = 'posts'
	ordering = ['-date_posted']
	paginate_by = 5


class UserPostListView(ListView):
	model = Post
	template_name = 'blog/user_posts.html'
	context_object_name = 'posts'
	paginate_by = 5

	def get_queryset(self):
		user = get_object_or_404(User, username=self.kwargs.get('username'))
		return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
	model = Post


class PostCreateView(LoginRequiredMixin, CreateView):
	model = Post
	fields = ['title', 'content']

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Post
	fields = ['title', 'content']

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.author:
			return True
		return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Post
	success_url = '/blog/'

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.author:
			return True
		return False


def about(request):
	return render(request, 'blog/about.html', {'title': 'About'})

home/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home/main.html')

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
	<h1>Django Blog</h1>
	<p>This blog was created with Django. It contains several functionalities including: </p>
	<ul class="list-group list-group-flush">
		<li class="list-group-item">Function based views and Class based views</li>
		<li class="list-group-item">Login required access</li>
		<li class="list-group-item">User specific template rendering</li>
		<li class="list-group-item">Pagination</li>
		<li class="list-group-item">CRUD functionalities</li>
		<li class="list-group-item">AWS S3 Bucket for files serving</li>
	</ul>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

	{% if title %}
	<title>Alexander Marino | Blog - {{ title }}</title>
	{% else %}
	<title>Alexander Marino | Blog</title>
	{% endif %}
</head>
<body>

	<header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
	    <div class="container">
	      <a class="navbar-brand mr-4" href="{% url 'blog:blog-home' %}">Django Blog</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
			<a class="nav-item nav-link" href="{% url 'home:main' %}">Portfolio</a>

	          <a class="nav-item nav-link active" href="{% url 'blog:blog-home' %}">Home</a>
	          <a class="nav-item nav-link" href="{% url 'blog:blog-about' %}">About</a>
			  {% if user.is_authenticated %}
			  	<a class="nav-item nav-link" href="{% url 'blog:post-create' %}">New Post</a>
			  {% endif %}
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
	          {% if user.is_authenticated %}
	            <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
	          	<a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>	
	          {% else %}
			    <a class="nav-item nav-link" href="{% url 'login' %}?next={{request.path}}">Login</a>
			    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
			  {% endif %}
	        </div>
	      </div>
	    </div>
	  </nav>
	</header>

	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-8">
	      {% if messages %}
	      	{% for message in messages %}
	      	  <div class="alert alert-{{ message.tags }}">
	      		{{ message }}  	
	      	  </div>
	      	{% endfor %}
	      {% endif %}
	      {% block content %}{% endblock %}
	    </div>
	    <div class="col-md-4">
	      <div class="content-section">
	        <h3>News</h3>
	        <p class='text-muted'>Recent Activity
	          <ul class="list-group">
	            <li class="list-group-item list-group-item-light">Latest Posts</li>
	            <li class="list-group-item list-group-item-light">Announcements</li>
	            <li class="list-group-item list-group-item-light">Calendars</li>
	            <li class="list-group-item list-group-item-light">New Users</li>
	          </ul>
	        </p>
	      </div>
	    </div>
	  </div>
	</main>

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
 
</body>
</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
	{% for post in posts %}
		<article class="media content-section">
		  <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
		  <div class="media-body">
		    <div class="article-metadata">
		      <a class="mr-2" href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}</a>
		      <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
		    </div>
		    <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
		    <p class="article-content">{{ post.content }}</p>
		  </div>
		</article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1"><<</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}"><</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">></a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">>></a>
      {% endif %}

    {% endif %}
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom md-4">Delete Post</legend>
				<h3>Are you sure you want to delete the post "{{ object.title }}"?</h3>
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-danger" type="submit">Delete</button>
				<a class="btn btn-outline-secondary" href="{% url 'blog:post-detail' object.id %}">Cancel</a>
			</div>
		</form>
	</div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
	<article class="media content-section">
	  <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
	  <div class="media-body">
	    <div class="article-metadata">
	      <a class="mr-2" href="{% url 'blog:user-posts' object.author.username %}">{{ object.author }}</a>
	      <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
	      {% if object.author == user %}
		    <div>
		      <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:post-update' object.id %}">Update</a>
		      <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:post-delete' object.id %}">Delete</a>
		    </div>
	      {% endif %}
	    </div>
	    <h2 class="article-title">{{ object.title }}</h2>
	    <p class="article-content">{{ object.content }}</p>
	  </div>
	</article>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom md-4">Blog Post</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Post</button>
			</div>
		</form>
	</div>
{% endblock content %}

blog/templates/blog/user_posts.html
{% extends "blog/base.html" %}
{% block content %}
  <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
	{% for post in posts %}
		<article class="media content-section">
		  <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
		  <div class="media-body">
		    <div class="article-metadata">
		      <a class="mr-2" href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}</a>
		      <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
		    </div>
		    <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
		    <p class="article-content">{{ post.content }}</p>
		  </div>
		</article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1"><<</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}"><</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">></a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">>></a>
      {% endif %}

    {% endif %}
{% endblock content %}